name: "Release devcontainer baseimage, features & Generate Documentation"
on:
  push:
    tags:
    - 'v*'
  # workflow_dispatch:

env:
  REGISTRY: ghcr.io
  DEVCONTAINER_CLI: 0.87.0

jobs:
  deploy:
    # if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get tag name
        run: echo "TAG=$(echo "${{ github.ref }}" | grep -oP 'refs/tags/v\K(.+)')" >> $GITHUB_ENV

      - name: Check that tag is set
        run: if [ -z "${{ env.TAG }}" ]; then { echo "Only releasing with tag!"; exit 2; }; fi

      - name: Docker Login
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Install devcontainer CLI"
        run: npm install -g @devcontainers/cli@${{ env.DEVCONTAINER_CLI }}

      - name: "Publish Baseimage to ghcr.io"
        env:
          IMAGE_BASE_NAME: "${{ env.REGISTRY }}/${{ github.repository }}"
        run: |
          set -e

          MINOR="$(echo "${{ env.TAG }}" | sed --regexp-extended 's/^([0-9]+\.[0-9]+)\.[0-9]+/\1/')"
          devcontainer build --push --no-cache=true --workspace-folder=./baseimage --image-name="${{ env.IMAGE_BASE_NAME }}:latest" --image-name="${{ env.IMAGE_BASE_NAME }}:$MINOR" --image-name="${{ env.IMAGE_BASE_NAME }}:${{ env.TAG }}" --log-level=debug

      - name: "Publish Features to ghcr.io"
        uses: devcontainers/action@v1
        with:
          publish-features: "true"
          base-path-to-features: "./src"
          generate-docs: "true"
          disable-repo-tagging: "true"
          oci-registry: ${{ env.REGISTRY }}
          devcontainer-cli-version: "${{ env.DEVCONTAINER_CLI }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR for Documentation
        id: push_image_info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          echo "Start."
          # Configure git and Push updates
          git config --global user.email github-actions[bot]@users.noreply.github.com
          git config --global user.name github-actions[bot]
          git config pull.rebase false
          branch=automated-documentation-update-$GITHUB_RUN_ID
          git checkout -b $branch
          message='Automated documentation update'
          # Add / update and commit
          git add */**/README.md
          git commit -m 'Automated documentation update [skip ci]' || export NO_UPDATES=true
          # Push
          if [ "$NO_UPDATES" != "true" ] ; then
              git push origin "$branch"
              gh pr create --title "$message" --body "$message"
          fi

